### ISSUE TITLE
Build process

### ISSUE THREAD

**Issue by piq9117** [codergvbrownsville/codergvb-pwa#2]
Setup circle ci for pre commit and pre push

**Comment by celgra** [comment]
Do issues #3 and #4 conflict if CRA would be used?

**Comment by piq9117** [comment]
No. the only issue i had with CRA last time was when i used the `ts` flag. CRA was just a luxury i was thinking. I'll try it but if its too much of a hassle i'll just hand roll my own webpack build.

**Comment by celgra** [comment]
Please keep your bigoted Webpack learnings away from my son and I.
